Update to level 1 fit function
cms-jet/JetMETAnalysis pull request #17
Opened 2019-02-04 20:31 UTC by aoverton0342

Moved jet_synchtest to jet_match, and changed some data handling internally to improve efficiency. Added new fitting functions, as well as sanity check plots to jet_syncfit. Fixed some bugs in SynchFittingProcedure, Style.h, and HistogramUtilities.

2019-02-19 07:46 UTC, ktht requested changes
Since you renamed `JetAnalyzers/bin/jet_synchtest_x.cc` to `JetAnalyzers/bin/jet_match_x.cc`, I'd also suggest to change `BuildFile.xml` accordingly.

2019-02-19 19:57 UTC, aoverton0342 commented
Just added the BuildFile as well as classes_def files

2019-02-22 04:55 UTC, ktht commented on JetAnalyzers/bin/BuildFile.xml
>  <bin   name="jet_synchtest_x"                  file="jet_synchtest_x.cc" />
Should be removed.

2019-02-22 04:57 UTC, ktht commented on JetUtilities/src/classes_def.xml
> +   <version ClassVersion="1" checksum="538640849"/>
This works only in CMSSW 10X but breaks in CMSSW 9X area.

2023-10-10 05:36 UTC, closed without merging